sudo: false
language: python
cache:
  directories:
    - $HOME/.cache/pip

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"

matrix:
  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "nightly"

install:
  - pip install --upgrade pip wheel
  - pip install Cython
  - pip install .

script:
  - nosetests -P tests

