sudo: false
language: python
cache:
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

matrix:
  include:
    - python: "3.7"
      sudo: true  # This may possibly be removed in the future
      dist: xenial
  allow_failures:
    - python: "nightly"

install:
  - pip install Cython tox-travis

script:
  - tox

jobs:
  include:
    - stage: deploy
      sudo: required
      services:
        - docker
      python: "3.6"
      install: python3 -m pip install Cython twine
      if: tag IS present
      script:
        - |
          python3 setup.py sdist
          ./buildwheels.sh
          ls -l dist/
          # Note: TWINE_PASSWORD is set in Travis settings
          python3 -m twine upload --repository-url https://test.pypi.org/legacy/ -u mmartin dist/*
