sudo: false
language: python
cache:
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

matrix:
  include:
    - python: "3.7"
      sudo: true  # This may possibly be removed in the future
      dist: xenial
  allow_failures:
    - python: "nightly"

install:
  - pip install Cython tox-travis

script:
  - tox
