language: python
python:
  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
  - "3.4"

install:
  - pip install --install-option="--no-cython-compile" cython
  - pip install .

script:
  - nosetests -P tests

